language: node_js
# There isn't much gained from testing on old versions of Node. This package is
# meant to run in a browser.
node_js:
  - "node"
addons:
  chrome: stable
  firefox: latest
  browserstack:
    forcelocal: true
    username:
      secure: JRAxx+LH8rdxy2435e08Yt1AfOperA5t7d4KVXTeSW7wTm7p9L6ha2I6CDuNFoSK0F9goIJKbKQM+YlMD2JhuBKnehrRGacwtA3eKgAYvOc2wXApjVyanYmZqdMIs+falswvraF289jn+Mbm9tzmR2WWaT/EBLyfjWizWTTiCiasGsOjemosao/Wv3mAslm2lcjcgIjYHqLPUuHv6HMefARbLc0ylA5G0LQGs2vL9w3KVs8Qgyn0ZecCLnnszXo/VDz28eZqEa4JCF/zzAU+2XdNZDi/jBwgg5/KJGbMomyWRAKAayNlYzVszyU4qf2ucaiXdjhWJ4xz9nzEzneojyvgbQc6NIthaoMDF41qvLCOgKqOnHvJxhUM832Qne+/Cm5DXDZqbRE35j5ms0XMnbtfSeEAHPDfHoiYcy6k3W7N6pnAWEms3maEwYjePI/npgDDw3egeX4azvvin0SKXLTf66bia6GO3WGNM24T0K7WYOZGGlyY0AuDLrrHL49uFVJMzoIRjYyw6r5IZn5TemU+V7BcNQjo64fA86k+aizR6Vbzclo69Si/JDZ3FfqqSUBKvdWjXxNcNBSwhsWUyDvQhxB6Y5h39sWs41dl8/hQ9RtKae/kUWbG6A3i7qAB+jMN6k8CrSna5uh0tIhWi9n1EeX384h3IB9yFFuIXJE=
    access_key:
      secure: ZdntyW1sMi8GTazydSqTtowjt6bHIrwYjUqqJDTkkiUlDWuj96yrmAzNVSbYUEfdTJ9181HtyDUwC20hVh1rX5CxrdIDrEBKd3FeRzO22CNNOQZFjz6p6C03Sp580CHa/z2CD+QgWkajorEJ/HRBGTvvxN7VtOe85+qOiYhst1yd7oG07hc38/1nvUGhbKuuZ+G8+d9YnE6v4qsLRmT9J2yKuxd893qzPZI+f4qHlApD2kcU8mC/KEtFW99UgSmYGOLJV6dDSSkWInjJ8VzHqWzNhDE9dXAWvULXTEwc4wa1X8Jyo34sxetaALw3zotSK8iOepUcyFzq0rxYavxb2lOCB4fUHTLVQ6IYQoi62A2Rb1w8NLWGTD2hnB635ZynNfcIq1zl5ARvAcYaPwKJhIIc++tifScWdtIpYb8lzgCRnUkOXczR7ahxgI8eIG0Clo3s7ORvVPmH1GOOyD9i43Dkd7XF21C4iqeK5F/QQeAqjEbpr9fOCdNslL6DIil20JbtoCG4NmwVLTWTFIjbqKDfJHP7ei2DhXYA5XHv57fBWcs2z3zxCIh/cT5qc4UDr9scjv72wXOeuHAbg7OlgF788/HvU0g1xg90DoMU91wan34FkUbbSwI7jZxdzTWjtGQMZ5jmXnVM1Z/DTZ9kGmOLVHzKqeA9RXLHfwI1AEw=
script: npm run build-and-test --browsers=all
