language: node_js
# There isn't much gained from testing on old versions of Node. This package is
# meant to run in a browser.
node_js:
  - "node"
addons:
  chrome: stable
  firefox: latest
  browserstack:
    forcelocal: true
    username:
      secure: "SaCn03ng10C96jB65Qiqd5+XZsH4lj/fLrOf6rwrmx6ng93PEdhz9+PeQF2ER/Krb/8nGIx4SOmI6Nm7hIFmMLcTUEZkFL+Z+NBhS7VMWJ1AalziBpCzOqRA/YwHZI/9fcRgpQLbM2vkkVVPMz6UcsQk5l2wjTAsCYwbysOPHnioZOBy8wKe/iSpmRSqBm33fBn9vhmB0NyPNxmZKQ/dviAFRaQoyvIcKC2vj5Dd8qb4ETWeK2zJn+UhS8aoaq3CCOIdgaSoqTglBbFbm3cCrtQWcY99M2f43G6jxVa+owgJi7kwFiabflYOoOQ8SFJpT+n1gHx1nGMnC+qVS5aPLu3hGFk43a1nyqUxQcJO6WojTBW+Uz9zUWA7dpIs3M7muMD/tE2eosY5xLeqVb+Q+LLJNctqupBBfdIFrYVnVsXBD9AkeQLszYZLMVqXsqKlEC0Wj30kdPQ81rC0unbyXnkOoKqvx9K0LdB5ErATr53BlyunGqfS2LrPjjyhZnb/XTuyHlnPS+mceLOgWPpEGVsqn463FyC+bbn3IeCiQpwGpYfC+EHWW6pZxaI0j2Bi59GsywV9RY9sHo+P5ZSItYXtWf5Uf4iDgZU3hb23/4G8g+yi6Op+txAY+ir4+m/3JXUFBlpu5ywhDdrbSa5g7lK7rhvTV4clGLDYeJky/gY="
    access_key:
      secure: "RtzgEKYyGoFs9CjMdGAOXKNpAoBDcgk+noTxsH2kr5KkTW0xambSCNOrF4x/igJWpsiPBtLksAaJ3/Du9CDp+Iz37PgrgjlmzSf0r9eL35AcTKzTQvZ4PtqHRHg7ckM4XqBQisGyBmLkiqopKW7OwLc09TCmlU5DfEraay6bOPU/ZUBZdpBoAoRL4s624AW1ecLtZ/E7w3yUfucD5ih+3BjzAYX0jgiL6DSwLllz0K8QDdeCdlmIzUSi0u2/GUI8VMDUjM+kSNc7IUYyZj7uhZcar26zil5airLp7GmfvpBBJrH5LnTXo7C45wPYtCxwOebo1xiz6vh3vMqqxWOC3rzopKRodKYS1GFZgl7fv7/oDbJIFXikiCH/a0gope6Z8TOuI07I4gCk3nvqsKV1uYn6VYaNYWJnAVWKm4L+ARg8h6axtpQRJ9vZwFqHU/gWz5sLR2FDTK6wfHGCnm4bWFDzHU/X/e2mf3TJ1lZ1SypdUD/jwF7GnuoVrqbqFCYIqFVDwYAwiAmkN/28ifItUFdbHUNoxzKX+elMbIspsMFvgRyoQYtFmxm48DvILn2Df6UGb3gAKNSGJbFestU4C3BQprIEUawqco8R0Ybj6FCtUFxT03eiVdAfuQY27ClGlkUYufSEccsuZNbzGum6sEJcCa4RBlJysXR7F4imt+8="
script: npm run build-and-test -- --browsers=all
